
spring:
  application:
    name: dsms
  datasource:
    #数据库配置
    driver-class-name: oracle.jdbc.OracleDriver
    username: vue
    password: vue123123
    url: jdbc:oracle:thin:@81.70.160.170:1521:vue
#服务器端口
server:
  port: 8080


mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package:
    com.SLotus.dsms.mybatis.entity


